export const PEN_REQUEST_BATCH_STUDENT_PROCESSING_SAGA = Object.freeze({

  INITIATED: 'INITIATED',

  VALIDATE_STUDENT_DEMOGRAPHICS: 'VALIDATE STUDENT DEMOGRAPHICS',

  PROCESS_PEN_MATCH: 'PROCESS PEN MATCH',

  PROCESS_PEN_MATCH_RESULTS: 'PROCESS PEN MATCH RESULTS',

  GATHER_REPORT_DATA: 'GATHER REPORT DATA',

  COMPLETED: 'COMPLETED',

  STARTED: 'STARTED',

  GET_STUDENTS: 'GET STUDENTS'

});
